server:
  port: 8080

spring:

  security:
    user:
      name: authorization
      password: authorization

  liquibase:
      enabled: true
      drop-first: true
      change-log: classpath:database-authorization-changelog.xml
      default-schema: auth
      liquibase-schema: auth

  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: authorization
      password: authorization
      driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: auth
    open-in-view: false